global using Hkust.Infra.Entities;
global using Hkust.Infra.IRepositories;
global using Hkust.Infra.Repository.EfCore.Repositories;
global using Hkust.Infra.Repository.EfCore.Transaction;
global using DotNetCore.CAP;
global using Microsoft.EntityFrameworkCore;
global using Microsoft.EntityFrameworkCore.Storage;
global using Microsoft.Extensions.DependencyInjection.Extensions;
global using System.Data;
